[env]
TERM = "xterm-256color"

[window]
padding = {x = 10, y = 10}
decorations = "None"
opacity = 0.8
blur = true

option_as_alt = "Both"

[font]

normal.family = "FiraCode Nerd Font Mono"

size = 16
